# Generated by Django 5.0.2 on 2024-02-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tag_alter_item_category_remove_item_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
